In [1]:
import pandas as pd
import numpy as np


In [2]:
##Import the excel file 
sensor_df = pd.read_csv('104.csv')

#Down sample to every 100
sensor_df_smol = sensor_df[0:10000:100]
sensor_df_smol.head()

sensor ID  norm_secs (secs)   time (days)
0        63802          0.000000  39416.607535
100     415483          4.500004  39416.607587
200     161919          9.000008  39416.607639
300     943442         12.500011  39416.607679
400     194738         16.500015  39416.607726

In [3]:
#filter to adjadent gateways with a time difference larger than 3 seconds
diff_sensor_df = sensor_df_smol.diff()
#print(diff_sensor_df[40:60])
#print(sensor_df_smol[40:60])
backbone_sensor_df = sensor_df_smol[diff_sensor_df['norm_secs (secs)'] > 3]
backbone_sensor_df.head()

sensor ID  norm_secs (secs)   time (days)
100     415483          4.500004  39416.607587
200     161919          9.000008  39416.607639
300     943442         12.500011  39416.607679
400     194738         16.500015  39416.607726
500     202164         20.000018  39416.607766

In [13]:
print(backbone_sensor_df.shape)
print(sensor_df_smol.shape)
#print(backbone_sensor_df['sensor ID'][0:10])
print(backbone_sensor_df[9:11])
print(backbone_sensor_df.iloc[10,1])
test = np.linspace(100,1000,10,dtype=int)
#index = np.linspace(100,(num_gates-1)*100,num_gates-1,dtype=int)
#print(index)
print(test)
print((test//100))

(23, 3)
(100, 3)
      sensor ID  norm_secs (secs)   time (days)
1000     117554         38.000034  39416.607975
1100     194738         41.500037  39416.608015
41.500036752881336
[ 100  200  300  400  500  600  700  800  900 1000]
[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
#set up a matrix of time between gateways, this is a proxy for distance
num_gates = backbone_sensor_df.shape[0]
time_pairs = np.ones((num_gates,num_gates))

for x in range(num_gates):
    #times = []
    for y in range(num_gates):
        #get all the pairs
        #times.append(abs(backbone_sensor_df.iloc[x][1] == backbone_sensor_df.iloc[y][1]))
        time_pairs[x][y] = abs(backbone_sensor_df.iloc[x][1] - backbone_sensor_df.iloc[y][1])
    #set the values
    #timenp.mean(times)
        
time_pairs

array([[ 0.        ,  4.50000399,  8.00000708, 12.00001063, 15.50001373,
        19.00001683, 22.50001993, 26.00002303, 29.50002613, 33.50002967,
        37.00003277, 40.50003587, 44.50003941, 48.00004251, 52.00004605,
        56.00004959, 59.50005269, 63.00005579, 66.50005889, 70.00006199,
        73.50006509, 76.50006775, 79.50007041],
       [ 4.50000399,  0.        ,  3.5000031 ,  7.50000664, 11.00000974,
        14.50001284, 18.00001594, 21.50001904, 25.00002214, 29.00002568,
        32.50002878, 36.00003188, 40.00003542, 43.50003852, 47.50004207,
        51.50004561, 55.00004871, 58.50005181, 62.00005491, 65.50005801,
        69.00006111, 72.00006376, 75.00006642],
       [ 8.00000708,  3.5000031 ,  0.        ,  4.00000354,  7.50000664,
        11.00000974, 14.50001284, 18.00001594, 21.50001904, 25.50002258,
        29.00002568, 32.50002878, 36.50003232, 40.00003542, 44.00003897,
        48.00004251, 51.50004561, 55.00004871, 58.50005181, 62.00005491,
        65.50005801, 68.5000

In [ ]:
#get the average velocity from the ground truth data 

In [ ]:
#calculate the distance matrix from the average time and average velocity 

In [ ]:
#pick three sensors to triangulate (the furthest apart ones)

In [ ]:
#derive all distances from the three sensors

In [ ]:
#plot the gateways 

In [ ]:
#compare gateway locations to ground truth 

In [ ]:
#backbone_sensor_df = sensor_df.loc(sensor_df['norm_secs (secs)'].diff() > 1)
#print(backbone_sensor_df)
#print(sensor_df.filter(sensor_df['norm_secs (secs)'].diff() > 1))
#backbone_sensor_df = sensor_df_smol.loc(diff_sensor_df['norm_secs (secs)'] > 1.0)
#backbone_sensor_df.head()

#print(sensor_df_smol[diff_sensor_df['norm_secs (secs)'] > 3])

##print(sensor_df['norm_secs (secs)'][100:110])
#print(sensor_df["sensor ID"][0])

#Get a pairwise matrix for the backbone gateways
num_gates = backbone_sensor_df.shape[0]
index = np.linspace(100,(num_gates-1)*100,num_gates-1,dtype=int)

#set up a matrix of time between gateways, this is a proxy for distance
time_pairs = np.ones((num_gates,num_gates))

for x in index:
    times = []
    for y in index:
        #get all the pairs
        if (backbone_sensor_df["sensor ID"][x+100] == backbone_sensor_df["sensor ID"][y]):
            times.append(abs(backbone_sensor_df["norm_secs (secs)"][x+100] - backbone_sensor_df["norm_secs (secs)"][y]))
        
        #set the distance values
        pairs[(x//100)-1][(y//100)-1] = np.mean(times)
        
#pairs

#if (backbone_sensor_df.iloc[x][1] == backbone_sensor_df.iloc[y][1]):